# Generated by Django 5.2.5 on 2025-09-07 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Requerimiento de Contacto', 'verbose_name_plural': 'Requerimientos de Contacto'},
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Requerimiento Antiguo', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Mensaje del Requerimiento'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('en_revision', 'En Revisión'), ('en_curso', 'En Curso'), ('cotizacion_enviada', 'Cotización Enviada'), ('aprobado', 'Aprobado'), ('finalizado', 'Finalizado'), ('descartado', 'Descartado')], default='ingresado', max_length=20, verbose_name='Estado del Requerimiento'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido de la Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Observación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor de la Observación')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='contact.contact', verbose_name='Requerimiento Asociado')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
